image:
  name: 'registry-gitlab.gog.com/docker/nodejs:10'

build:
    script:
      - npm ci
      - npm run build
      - npm run test
    except:
      - master

publish:
    script:
      - npm ci
      - echo //$NPM_REGISTRY/:_authToken="$AUTH_TOKEN">.npmrc
      - npm run publish-please --ci
    only:
      - master
