build:
    script:
      - npm install
      - npm run build
      - npm run test
    except:
      - master

publish:
    script:
      - npm install
      - echo '//$NPM_REGISTRY/:_authToken="$AUTH_TOKEN"'>.npmrc/
      - npm run publish-please --ci
    only:
      - master
